### ISSUE TITLE
App archive fails validation due to invalid plist file on Xcode 15.3

### ISSUE THREAD

**Issue by cameroncooke** [AppsFlyerSDK/AppsFlyerFramework#263]
# Report

## SDK Version
`6.13.0`

## What did you do?
Build for archive and validated on App Store Connect

## What did you expect to happen?
Archive to pass validation

## What happened instead?
Archive failed validation with the following errors:

```shell
Error
Invalid Bundle. The bundle MyApp.app/Frameworks/AppsFlyerLib.framework does not support the minimum OS Version specified in the Info.plist.
```

## Please provide any other relevant information.
This started with the release of Xcode 15.3, this also happens for other 3rd party libraries for which I've already raised tickets and they already have fixes in the works:

https://github.com/google/GoogleAppMeasurement/issues/62
https://github.com/firebase/firebase-ios-sdk/issues/12441

This is currently blocking our ability to release on Xcode Cloud when using the "Latest version" Xcode stratergy.

**Comment by MilesV64** [comment]
We are also having this issue!

**Comment by williamkey123** [comment]
I'm having this issue as well; looks like it became an issue with Xcode 15.3. Until AppsFlyer fixes this, you can follow the instructions here to get Xcode cloud to use Xcode 15.2:

https://github.com/firebase/firebase-ios-sdk/issues/12441#issuecomment-1971577317

> You can set the Xcode version for Xcode Cloud builds within App Store Connect -> Xcode Cloud -> Manage Workflows -> Workflow -> Xcode version. The default value is "Latest Release" which is currently Xcode 15.3 RC.

Once you do this, you should be able to re-run your workflow and build the app.

**Comment by zavsby** [comment]
Seems to be a blocker to use Xcode 15.3 for us also.
@af-obodovskyi Could you take a look please?

**Comment by af-obodovskyi** [comment]
We will investigate this issue and come up with the solution, thank you!

**Comment by danniss10** [comment]
Also seeing this issue!

**Comment by vince1393** [comment]
Seeing this issue as well!

**Comment by slagunes** [comment]
Same issue too ☹️

**Comment by frangrolemund** [comment]
> We will investigate this issue and come up with the solution, thank you!

According to the [esteemed Eskimo](https://forums.developer.apple.com/forums/thread/705297?answerId=711975022#711975022), the minimum os version in the binary doesn't match the Info.plist.  I used his instructions and found the following in the latest release of the framework (6.13.1):
- the AppsFlyerLib reports `16.0`
- the Info.plist reports `8.0`
...
Hope this helps.

**Comment by vince1393** [comment]
Any updates on this? Somewhat urgent as we have a release upcoming next week that relies on Xcode 15.3 APIs.

**Comment by abuljaleel** [comment]
Seeing this issue, Xcode 15.3

**Comment by alighani-zoral** [comment]
Hello, We are also facing this issue

`Invalid Bundle. The bundle Digibank.app/Frameworks/AppsFlyerLib.framework does not support the minimum OS Version specified in the Info.plist. (ID: 361cad90-ce1f-4f38-b373-6f31bec39f8a)`

We have a critical release pending to be release and we are using xcode 15.3 and unable to upload on Testflight.

Please suggest a fix for this

**Comment by jamesyorke** [comment]
Same here!

**Comment by vince1393** [comment]
> Did anyone checked it with latest 6.13.1 version?

I tried 6.13.0 and had the same issue, haven't had a chance to check 6.13.1 yet

**Comment by jamesyorke** [comment]
> Did anyone checked it with latest 6.13.1 version?

Can confirm `6.13.1` also still has the issue.

**Comment by vince1393** [comment]
Looks like the firebase SDKs have been fixed. Just waiting on this one. @af-obodovskyi do we have an ETA for this?

**Comment by guppy-jpf** [comment]
yet another me-too ...

**Comment by gooson** [comment]
+1

**Comment by sroyaura** [comment]
+1

**Comment by bcherry** [comment]
+1

**Comment by dmallory** [comment]
For anyone trying to work around this manually, I can confirm that setting `MinimumOSVersion` to `16.0` in the framework's `Info.plist` resolves this and passes validation. The version in there is `8.0` so must be very stale and not getting updated when it's built, somehow.

**Comment by af-obodovskyi** [comment]
We are aiming to release a fix for this issue and searching for the best aproach. The planned release date for the SDK version `v6.13.2` with fix is March 25th.

**Comment by frangrolemund** [comment]
> We are aiming to release a fix for this issue and searching for the best aproach. The planned release date for the SDK version `v6.13.2` with fix is March 25th.

Are you aware that this issue in your SDK also prevents uploading to TestFlight for general QA activities?   This unfortunately leaves many of us with the choice between two weeks of stalled QA and hacking your code for you so that we can make progress with an unofficial binary we shouldn't ship anyway.  If we can take @dmallory at his word, this is an about a 1 minute change to address right now.  I'd argue that a component of the best approach is to get your consumers running again.  Somehow Google had their entire SDK updated almost instantly.

**Comment by vince1393** [comment]
This is a serious issue for us, currently blocking important code from being merged that relies on the 15.3 compiler. March 25th is a very long wait time for something that appears to be a one-line fix.

**Comment by dmallory** [comment]
> > For anyone trying to work around this manually, I can confirm that changing the `MinimumOSVersion` to `16.0` in the framework's `Info.plist` resolves this and passes validation. The version in there is `9.0` as noted above, seems very stale.
> 
> 
> 
> Just to expand on this for people. I archived the build manually (ignoring my usual process), then after archiving, right click > show in finder. Right click > show package contents > Products > Applications > Right click your app > Show Package Contents > Frameworks > AppFlyer and here is where you do dmallory's `MinimumOSVersion` change in `Info.plist`.  This should get you through whilst we wait until the 25th March

Yes, any method of getting that final `Info.plist` edited should work. I switched it to a local SPM binary with my own `Package.swift` pointing to the edited framework since we validate builds frequently through CI, but editing manually or with a script before submit works, or you could probably fork this repo just to point to your own edited framework with it updated.

**Comment by danniss10** [comment]
Agree with @cameroncooke here! March 25th is a really long timeline for this fix and manually editing bundles is not an appropriate solution. We are blocked from releasing the next version of our app until this fix is released. Is there anyway to increase the urgency on resolving this issue?

**Comment by guppy-jpf** [comment]
we had the same issue with another analytics framework, repro, (annoyingly, no issue tracker exposed on their github page) ... and were told by their support staff that their engineers consider this an apple issue and that:

> - Xcode 15.3 performs a new check that validates that your project version is lesser or equal to "MinimumOSVersion" of all embedded dynamic frameworks. That is obviously wrong and it should be greater or equal.
> - google/firebase uses a hack that just set the MinimumOSVersion to 100.0 to pass this new check.

[please disregard any "tone"-related reactions you might have to those responses; i think they are using machine translation to communicate in english] 

i have an open question with repro, asking them for evidence of their claim, but haven't heard back yet.  i couldn't find any evidence that that was google's solution, and the issue over there is closed, so i can't ask w/o opening a new one ... 

they also state that:

> AppsFlyerFramework like us, acknowledges that there is a problem, but they seem to be in the same position as us, not wanting to use that hack and waiting for Apples fix.

@af-obodovskyi -- from your comment above, it doesn't sound like appsflyer is "waiting for apple's fix" ... can you please comment on what form your fix is expected to take, and if you feel that this is actually working around an apple bug, or if it's just a necessary update to address a stricter (but not necessarily erroneous) set of checks in xcode 15.3?

also, if anyone knows more detail about what google's actual solution was, it would be interesting to know.

thanks!

**Comment by 4refael** [comment]
Unless you have to use 15.3, reverting back to Xcode 15.2 was the easiest solution for me.

**Comment by georgbachmann** [comment]
> > For anyone trying to work around this manually, I can confirm that changing the `MinimumOSVersion` to `16.0` in the framework's `Info.plist` resolves this and passes validation. The version in there is `9.0` as noted above, seems very stale.
> 
> Just to expand on this for people. I archived the build manually (ignoring my usual process), then after archiving, right click > show in finder. Right click > show package contents > Products > Applications > Right click your app > Show Package Contents > Frameworks > AppFlyer and here is where you do dmallory's `MinimumOSVersion` change in `Info.plist`. This should get you through whilst we wait until the 25th March

Thanks a lot for that tip. I am just wondering cause it's a compiled plist... how do you change the min-version? Do you convert the plist back and forth?

It's really shocking to me that a bug that is preventing users from uploading a build it not important enough to AppsFlyers for a quick fix update... @af-obodovskyi

**Comment by af-obodovskyi** [comment]
We have precisely investigated this issue with our latest build on Xcode 15.3 and played around with validating and publishing builds with all different kinds of DM options, like embedding raw frameworks to the project, CocoaPods integration, Carthage integration and etc. 

As a result of this investigation we have reproduced and confirmed, that the issue exists only on our SPM statically-linked projects (`AppsFlyerFramework` and `AppsFlyerFramework-Strict`). 

There are multiple ways of solving this bug, which we consider actually, as an Apple bug, because no minimum deployment target restrictions have been specified in the release notes to the Xcode 15.3. 

1. The most unwanted solution for us is using `minimumOSTarget = 100` this approach may lead to some unpredictable behaviour in the future. We do not know how the system or AppStoreConnect validation service will handle it. 
2. The second solution from our side might be updating the minimum deployment target. For this we have to make some analysis before the implementation to understand all the consequences of this decision. We still have a lot of customers who rely on older iOS versions, that is why it is not easy and fast for us to take such decisions.
3. Wait for possible Apple fix. 

As a temporary workaround we suggest you to try using [AppsFlyerFramework-Dynamic](https://github.com/AppsFlyerSDK/AppsFlyerFramework-Dynamic) target. After multiple tests we can verify, that this should work and should be able to unblock our customers, so they can proceed with the deployment process. If you try this, please reach out to us and leave your feedback on this solution wether it was successful or not.

**Comment by via-guy** [comment]
I found other reports of issues with frameworks related to Xcode 15.3. It seems to be a common consensus that this is an Apple bug and it's recommended to downgrade back to Xcode 15.2 in order to fix uploading apps to the App Store.

**Comment by georgbachmann** [comment]
> We have precisely investigated this issue with our latest build on Xcode 15.3 and played around with validating and publishing builds to AppStoreConnect with all different kinds of DM options, like embedding raw frameworks to the project, CocoaPods integration, Carthage integration and etc.
> 
> As a result of this investigation we have reproduced and confirmed, that the issue exists only on our SPM statically-linked projects (`AppsFlyerFramework` and `AppsFlyerFramework-Strict`).
> 
> There are multiple ways of solving this bug, which we consider actually, as an Apple bug, because no minimum deployment target restrictions have been specified in the release notes to the Xcode 15.3.
> 
> 1. The most unwanted solution for us is using `minimumOSTarget = 100` this approach may lead to some unpredictable behaviour in the future. We do not know how the system or AppStoreConnect validation service will handle it.
> 2. The second solution from our side might be updating the minimum deployment target. For this we have to make some analysis before the implementation to understand all the consequences of this decision. We still have a lot of customers who rely on older iOS versions, that is why it is not easy and fast for us to take such decisions.
> 3. Wait for possible Apple fix.
> 
> As a temporary workaround we suggest you to try using [AppsFlyerFramework-Dynamic](https://github.com/AppsFlyerSDK/AppsFlyerFramework-Dynamic) target. After multiple tests we can verify, that this should work and should be able to unblock our customers, so they can proceed with the deployment process. If you try this, please reach out to us and leave your feedback on this solution wether it was successful or not.

@af-obodovskyi Thanks a lot for your detailed reply! Will downgrade to Xcode 15.2 for the time being.

**Comment by frangrolemund** [comment]
> As a temporary workaround we suggest you to try using [AppsFlyerFramework-Dynamic](https://github.com/AppsFlyerSDK/AppsFlyerFramework-Dynamic) target. After multiple tests we can verify, that this should work and should be able to unblock our customers, so they can proceed with the deployment process. If you try this, please reach out to us and leave your feedback on this solution wether it was successful or not.

Is this supposed to work with SPM in Xcode?  It identified the package:

<img width="1110" alt="Screenshot 2024-03-14 at 12 07 02 PM" src="https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/11785548/9bc52429-d066-434f-8f7c-5059d3688ea1">


...but then failed to add to the project:

<img width="1047" alt="Screenshot 2024-03-14 at 12 09 16 PM" src="https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/11785548/9f9302b5-8747-47c7-a9ae-666cd4693e98">

**Comment by frangrolemund** [comment]
> @frangrolemund yes, it should, try to clear your SPM cache and try to pull the dependency one more time. Just delete the folder in this repository `~/Library/Caches/org.swift.swiftpm`
> 

Looks like it was a latent failure in another third-party library and an unhelpful error when it got to yours.  I can confirm that swapping to this framework was accepted by App Store Connect using Xcode `15.3`.  Thanks for the help.

**Comment by cameroncooke** [comment]
It’s worth pointing out it’s an assumption that it’s an Apple bug. It seems
to be App Store Connect rejecting the build not specifically Xcode. It’s
not clear if it’s an issue of the build itself or that newer builds are
validated to a stricter ruleset by App Store Connect.

It’s of course quite possible it’s a bug so should probably be raised as
such. That all said we do need a reasonable solution regardless of fault.


Cameron.

**Comment by guppy-jpf** [comment]
> Have you guys reached out to Apple regarding this issue and filed a bug report through Feedback?

i know that [google/firebase have filed a bug](https://github.com/firebase/firebase-ios-sdk/pull/12439#issuecomment-1996169992) for a similar issue (FB13657402)

**Comment by clara-ia** [comment]
@af-obodovskyi Firebase appear to have tracked this down and already pushed a fix here - https://github.com/firebase/firebase-ios-sdk/pull/12414 - with details in this issue case - https://github.com/firebase/firebase-ios-sdk/issues/12441 - hopefully you can do something similar to resolve please AppsFlyer?

**Comment by leearmstrong** [comment]
AppsFlyer, any progress with your approach?  You charge silly amounts for your service and can't get in gear for this!

**Comment by leearmstrong** [comment]
![giphy](https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/82891/ecc9e521-9452-43ce-aa32-f04d449abb90)

**Comment by vince1393** [comment]
> We are aiming to release a fix for this issue and searching for the best aproach. The planned release date for the SDK version `v6.13.2` with fix is March 25th.

@af-obodovskyi Any ETA? Initially we were told the fix would be in today and im not seeing a release anywhere

**Comment by af-obodovskyi** [comment]
The issue should be fixed in `v6.13.2` for the SPM. Please, refer to this [**documentation**](https://github.com/AppsFlyerSDK/AppsFlyerFramework?tab=readme-ov-file#SPM) when you update your Swift package. Thank you for your patience and pressious time. 

A small update on the Apple issue: As previously mentioned, it is an Apple bug, but it is not related to the minimumOSVersion validation. After our further investigation, we have discovered a possible bug in Xcode 15.3 build system. When compiling a project with a statically linked framework, if we open the app bundle from the archive, we can see a Frameworks folder with a dummy AppsFlyerLib.framework, which is approximately 45 KB in size. For statically linked frameworks, such a folder should not exist. I suspect that when we push the build to the App Store Connect, it tries to validate the .plist of this dummy binary. We will prepare all corresponding information and will issue a ticket to Apple Support.

**Comment by clara-ia** [comment]
@leearmstrong they did but they already released a patch for it, see my comment above https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/263#issuecomment-2000134896

**Comment by leearmstrong** [comment]
@clara-ia Exactly my point, I think AppsFlyer are missing this!

I am recommending to our team we move away ASAP from AppsFlyer

**Comment by georgbachmann** [comment]
> The issue should be fixed in `v6.13.2` for the SPM. Please, refer to this [**documentation**](https://github.com/AppsFlyerSDK/AppsFlyerFramework?tab=readme-ov-file#SPM) when you update your Swift package. Thank you for your patience and pressious time.

Well... @af-obodovskyi this is a big SHOULD :) cause no it's NOT fixed?!? I am on 6.13.2 (AppsFlyerLib-Static). I am still getting the same error! Do we now have to wait an other two weeks so it fit's into your release cycle to really fix it? I really don't understand it... Why???? Would it have been so hard to test that yourself before releasing it?

**Comment by af-obodovskyi** [comment]
@georgbachmann fixed, please reset your SPM cache and try again.

**Comment by leearmstrong** [comment]
Huh?  So you bumped the release and changed the code, but not the version? 

I know you've done this before, why not keep distinct versions so this would be 6.13.3?  This is crazy.

**Comment by cameroncooke** [comment]
So it's closed as fixed but apparently it was an Apple but? 🤔🤷‍♂️

**Comment by wsb9** [comment]
Still reproducible. AppStore does not accepting builds even after resetting SPM cache (multiple times). 

Xcode 15.3 
AppsFlyer 6.13.2

**Comment by ob1vansk1y** [comment]
@wsb9 Could you, please, share your logs and the link to the github repo from which you pull the AppsFlyer dependency?

**Comment by kselvin** [comment]
I archived/uploaded with the dynamically linked version instead a warning 

"Architecture incompatible with MinimumOSVersion." 

but it still let me upload to App store.  Is this ok?   I do not know what that means

**Comment by kselvin** [comment]
<img width="403" alt="Screenshot 2024-03-26 at 6 58 39 PM" src="https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/14080338/e2ca797b-380b-4069-82ea-f891dc250cd6">

**Comment by jamesyorke** [comment]
This is not fixed

**Comment by af-obodovskyi** [comment]
I have created [a small sample app](https://github.com/af-obodovskyi/spm-archive-sampleApp) so you will be able to verify, that the solution with the SPM works propperly. Please, follow the readme carefully and repeat all steps to be able to test propperly.

**Comment by T-Pham** [comment]
@af-obodovskyi, the issue persists on tvOS, at least for the Strict library, for us. I guess the fix didn't get applied to the tvOS framework files?

**Comment by af-obodovskyi** [comment]
@T-Pham, thank you for your comment, reopening the issue. 
We will adapt our solution and will release a fix as we test and verify, that all platforms are covered with the fix ASAP.

**Comment by wsb9** [comment]
@ob1vansk1y tried w new repo -- works OK for iOS now. Thanks!

**Comment by Faizan-Seera** [comment]
Still getting the issue 
Xcode 15.3
AppsFlyer 6.13.2
Invalid Bundle. The bundle Lumi.app/Frameworks/AppsFlyerLib.framework does not support the minimum OS Version specified in the Info.plist.

**Comment by skapur1424** [comment]
I am still getting this issue with iOS. I don't use tvOS. I am using 6.13.2. I have been waiting to upload for weeks now. I may be forced to remove AppsFlyer to do a release. Please help.

**Comment by af-obodovskyi** [comment]
@skapur1424 @Faizan-Seera 
Did you try this? 

https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/263#issuecomment-2025576536

**Comment by af-obodovskyi** [comment]
> I am still getting this issue with iOS. I don't use tvOS. I am using 6.13.2. I have been waiting to upload for weeks now. I may be forced to remove AppsFlyer to do a release. Please help.
> 
> I am also now seeing the sample app which specifies 3 possible repos (static, dynamic or strict). So is the main repo (https://github.com/AppsFlyerSDK/AppsFlyerFramework) not valid for now? How do I know which of the 3 new repos to use? If I was using the main repo before, which one should I use?

Please use 
https://github.com/AppsFlyerSDK/AppsFlyerFramework-Static

**Comment by skapur1424** [comment]
It worked! Thank you @af-obodovskyi ! for the real-time responsiveness!

**Comment by T-Pham** [comment]
Hi @af-obodovskyi, do you have a timeline for the fix on tvOS? The issue is a blocker for us.

**Comment by bigMOTOR** [comment]
> The issue should be fixed in `v6.13.2` for the SPM. Please, refer to this [**documentation**](https://github.com/AppsFlyerSDK/AppsFlyerFramework?tab=readme-ov-file#SPM) when you update your Swift package. Thank you for your patience and pressious time.

@af-obodovskyi hi, I've just tried 6.13.2 and the issue still stands for me

**Comment by T-Pham** [comment]
Hi @af-obodovskyi, could you please confirm whether the 6.14.0 release contains a fix for this issue on tvOS? (I couldn't verify that myself because I ran into an unrelated issue with checksum). Thank you!

**Comment by af-obodovskyi** [comment]
@bigMOTOR 

https://github.com/AppsFlyerSDK/AppsFlyerFramework/issues/263#issuecomment-2025576536

**Comment by af-obodovskyi** [comment]
@T-Pham ready with the fix, please clean your SPM cache and try again to deploy your tvOS app. If you face any issues, please feel free to ping me.

**Comment by adamrushy** [comment]
@af-obodovskyi 

Please check the SPM checksum I am getting this error when downloading the latest version:

`checksum of downloaded artifact of binary target 'AppsFlyerLib' (e3063f25dd58b242c31d1bc5761fcb96930539e8e4d0745c22df792ecbd455e0) does not match checksum specified by the manifest (d7fdf61996dacb7787506305b6c541197ede64fcc4528c41842d9a507bd1b94b)`

**Comment by adamrushy** [comment]
> @adamrushy please, clear SPM cache in the directory `~/Library/Caches/org.swift.swiftpm/`

@af-obodovskyi I tried this twice, including "Reset package cache"

I also created a brand new sample project and installing from fresh (see screenshot).

<img width="1512" alt="Screenshot 2024-04-08 at 13 39 35" src="https://github.com/AppsFlyerSDK/AppsFlyerFramework/assets/1519998/992f5db4-dd39-4989-8c5b-7bc3ed920975">

**Comment by DenTelezhkin** [comment]
@af-obodovskyi Thanks for update!
Unfortunately, using https://github.com/AppsFlyerSDK/AppsFlyerFramework-Static did not work for us, as we also use https://github.com/AppsFlyerSDK/appsflyer-apple-purchase-connector, which also does not pass AppStoreConnect validation.

The only variant right now, that does pass validation, is using https://github.com/AppsFlyerSDK/PurchaseConnector-Dynamic along with https://github.com/AppsFlyerSDK/AppsFlyerFramework-Dynamic, however:

1. There is still warning, while uploading to AppStoreConnect  `Architecture incompatible with MinimumOSVersion. The app bundle at '***.app/Frameworks/AppsFlyerLib.framework' specifies a MinimumOSVersion of '100.0' but contains a 32-bit architecture that is unsupported on iOS 12 and later.`
2. When application is running, there are warnings in console about duplicate implementations (which are included in both frameworks) - previously we were using static versions of both frameworks, thus avoiding undefined behavior:
```
Class AFSDKException is implemented in both /private/var/containers/Bundle/Application/2FFFCB0E-B0C7-40D5-B9A0-A8F3CF8091CE/***.app/Frameworks/PurchaseConnector.framework/PurchaseConnector (0x106a2dbd8) and /private/var/containers/Bundle/Application/2FFFCB0E-B0C7-40D5-B9A0-A8F3CF8091CE/***.app/Frameworks/AppsFlyerLib.framework/AppsFlyerLib (0x1053779e8). One of the two will be used. Which one is undefined.

... And many more
```

Are there plans to rollout this fix for PurchaseConnector?

**Comment by bigMOTOR** [comment]
@af-obodovskyi Thank you for your response.
Unfortunately, I wasn't able to switch to static/dynamic versions. We use AppsFlyer as a part of common core shared across our apps via SPM.
I tried to change `.package(url: "https://github.com/AppsFlyerSDK/AppsFlyerFramework-Static", .upToNextMajor(from: "6.14.0" )) ` with `.product(name: "AppsFlyerLib", package: "AppsFlyerFramework-Static")` in targets section  or Dynamic as well. But I've get an error `product 'AppsFlyerLib' required by package not found in package 'AppsFlyerFramework-Dynamic'`

Thank you

**Comment by RonKliffer** [comment]
I'm experiencing issues too, getting the following:
Revision 19c1c5c476d431e381f35c8c99a2fe6435085207 for appsflyerframework-static remoteSourceControl https://github.com/AppsFlyerSDK/AppsFlyerFramework-Static version 6.14.0 does not match previously recorded value 935dd2a4122e04133c067cb43215888ec93f00fa

**Comment by af-obodovskyi** [comment]
@bigMOTOR 
Here is verified solution.
Please remove SPM caches from following directories 
```
rm -rf ~/Library/Caches/org.swift.swiftpm
rm -rf ~/Library/org.swift.swiftpm

Optionally: 
rm -rf ~/.swiftpm
```

Delete derived data and clean the project.

**Comment by T-Pham** [comment]
Thanks, @af-obodovskyi. Confirmed that 6.14.0 has fixed the issue on tvOS as well!

**Comment by guppy-jpf** [comment]
fyi, this issue seems to be fixed, at least for us, in xcode 15.4 ...
we're still using appsflyer 6.12.2, and had been manually doing the "version 100" workaround when building w/ xcode 15.3, but, even though i couldn't find anything pertinent in the release notes to indicate that apple had changed anything, the 15.4 build/uploads i did today were processed with no errors.

**Comment by eyale** [comment]
works fine with Xcode 15.4 - just download new version of Xcode.
